name: Auto set project

on:
  workflow_call:
    inputs:
      project-number:
        description: 'The project-number of https://github.com/orgs/<owner>/projects/<project-number>'
        required: true
        type: number
      project-owner-user:
        description: 'User name of project owner.'
        required: false
        type: string
      project-owner-org:
        description: 'Organization name of project owner.'
        required: false
        default: ${{ github.repository_owner }}
        type: string
      field-names:
        description: 'Comma separated field names will update it after add issue to project.'
        required: false
        type: string
      field-values:
        description: 'Comma separated values will update it after add issue to project.'
        required: false
        type: string
      add-labels:
        description: 'Labels to add to an issue, seperated by commas.'
        required: false
        type: string
    secrets:
      github-token:
        description: 'Personal access token to use to update project. Requires `repo`, `org:read` and `org:write` permissions.'
        required: true

jobs:
  set-project:
    name: Set project
    runs-on: ubuntu-latest
    env:
      project_url: "https://github.com/orgs/${{ inputs.project-owner-user || inputs.project-owner-org }}/projects/${{ inputs.project-number }}"
    steps:
      - name: Add to project
        uses: actions/add-to-project@960fbad431afda394cfcf8743445e741acd19e85
        id: add-to-project
        with:
          project-url: ${{ env.project_url }}
          github-token: ${{ secrets.github-token }}

      - name: Update fields
        if: inputs.field-names
        uses: titoportas/update-project-fields@421a54430b3cdc9eefd8f14f9ce0142ab7678751
        with:
          project-url: ${{ env.project_url }}
          github-token: ${{ secrets.github-token }}
          item-id: ${{ steps.add-to-project.outputs.itemId }}
          field-keys: ${{ inputs.field-names }}
          field-values: ${{ inputs.field-values }}

      - name: Add labels
        if: inputs.add-labels
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: ${{ inputs.add-labels }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
